server:
   port: 8063
spring.datasource.url: jdbc:h2:file:./camunda-h2-database
   

spring:
   codec:
      max-in-memory-size: 15MB
   mail:
      host: smtp.gmail.com
      port: 587
      username: ing.victorcamacho@gmail.com
      password: cnztazalfnwryqhx
      properties:
         mail:
            smtp:
               auth: true
               connectiontimeout: 5000
               timeout: 5000
               writetimeout: 5000
               starttls:
                  enable: true
      
  
      
      
      
      
      


camunda.bpm.admin-user:
  id: demo
  password: demo